# Generated by Django 3.2.18 on 2023-06-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], default='male', max_length=15)),
                ('number', models.CharField(max_length=15)),
                ('boarding', models.CharField(max_length=20)),
                ('depature', models.CharField(max_length=20)),
                ('adaar', models.IntegerField(max_length=12)),
            ],
        ),
    ]
