# Generated by Django 3.2.18 on 2023-06-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='adaar',
            field=models.IntegerField(),
        ),
    ]
