# Generated by Django 3.2.18 on 2023-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbooking', '0002_alter_passenger_adaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
