# Generated by Django 3.2.18 on 2023-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbooking', '0004_remove_passenger_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(blank=True, default='male', max_length=15),
        ),
    ]
